
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Da Silva
 */
public class StudentAttendenceSystem extends javax.swing.JFrame {

    /**
     * Creates new form StudentAttendenceSystem
     */
    public StudentAttendenceSystem() {
        initComponents();
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        branchbtn = new javax.swing.JButton();
        viewstdntbtn = new javax.swing.JButton();
        atndncebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dailybtn = new javax.swing.JButton();
        monbtn = new javax.swing.JButton();
        sembtn = new javax.swing.JButton();
        udtlbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        stdntbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        homebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homebtn.setText("HOME");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        branchbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        branchbtn.setText("BRANCH DETAIL");
        branchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchbtnActionPerformed(evt);
            }
        });

        viewstdntbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewstdntbtn.setText("VIEW ALL STUDENTS");
        viewstdntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstdntbtnActionPerformed(evt);
            }
        });

        atndncebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        atndncebtn.setText("ATTENDENCE");
        atndncebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atndncebtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("RESULTS");

        dailybtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dailybtn.setText("DAILY");
        dailybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailybtnActionPerformed(evt);
            }
        });

        monbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        monbtn.setText("MONTHLY");
        monbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monbtnActionPerformed(evt);
            }
        });

        sembtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sembtn.setText("SEM");
        sembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembtnActionPerformed(evt);
            }
        });

        udtlbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        udtlbtn.setText("USER DETAIL");
        udtlbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udtlbtnActionPerformed(evt);
            }
        });

        logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutbtn.setText("LOGOUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        stdntbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stdntbtn.setText("STUDENT DETAILS");
        stdntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdntbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dailybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atndncebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdntbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewstdntbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(branchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addComponent(monbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sembtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(udtlbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(homebtn)
                .addGap(28, 28, 28)
                .addComponent(branchbtn)
                .addGap(27, 27, 27)
                .addComponent(stdntbtn)
                .addGap(27, 27, 27)
                .addComponent(viewstdntbtn)
                .addGap(31, 31, 31)
                .addComponent(atndncebtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dailybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(monbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sembtn)
                .addGap(53, 53, 53)
                .addComponent(udtlbtn)
                .addGap(30, 30, 30)
                .addComponent(logoutbtn)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Da Silva\\Desktop\\istockphoto-538665734-612x612.jpg")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("''STUDENT ATTENDENCE MANAGEMENT SYSTEM''");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        StudentAttendenceSystem sa = new StudentAttendenceSystem();
        sa.setVisible(true);
    }//GEN-LAST:event_homebtnActionPerformed

    private void branchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        BRANCH_DETAIL b = new BRANCH_DETAIL();
       b.setVisible(true);
    }//GEN-LAST:event_branchbtnActionPerformed

    private void stdntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdntbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Student_Detail sd = new Student_Detail();
        sd.setVisible(true);
    }//GEN-LAST:event_stdntbtnActionPerformed

    private void viewstdntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstdntbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        All_Students a = new All_Students();
        a.setVisible(true);
    }//GEN-LAST:event_viewstdntbtnActionPerformed

    private void atndncebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atndncebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ATTENDENCE a = new ATTENDENCE();
        a.setVisible(true);
    }//GEN-LAST:event_atndncebtnActionPerformed

    private void dailybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailybtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        DAILY_ATTENDENCE da = new DAILY_ATTENDENCE();
        da.setVisible(true);
    }//GEN-LAST:event_dailybtnActionPerformed

    private void monbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        MONTHLY_ATTENDENCE ma = new MONTHLY_ATTENDENCE();
        setVisible(true);
    }//GEN-LAST:event_monbtnActionPerformed

    private void sembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        SEMESTER_ATTENDENCE sa = new SEMESTER_ATTENDENCE();
        setVisible(true);
    }//GEN-LAST:event_sembtnActionPerformed

    private void udtlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udtlbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        USER_DETAIL ua = new USER_DETAIL();
        setVisible(true);
    }//GEN-LAST:event_udtlbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAttendenceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAttendenceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAttendenceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAttendenceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAttendenceSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atndncebtn;
    private javax.swing.JButton branchbtn;
    private javax.swing.JButton dailybtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton monbtn;
    private javax.swing.JButton sembtn;
    private javax.swing.JButton stdntbtn;
    private javax.swing.JButton udtlbtn;
    private javax.swing.JButton viewstdntbtn;
    // End of variables declaration//GEN-END:variables
}
